version: '3'

services:
  result:
    build: ./result
    restart: always
    ports:
      - "5001:80"
    networks:
      - result-tier
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "db-data:/var/lib/postgresql/db"
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - result-tier
      - back-tier
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  poll:
    build: ./poll
    restart: always
    ports:
      - "5000:80"
    networks:
      - poll-tier
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:7.0
    restart: always
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
    environment:
      - HOSTNAME=redis

  worker:
    build: ./worker
    restart: always
    networks:
      - back-tier
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis
    depends_on:
      - redis
      - db

volumes:
  db-data:

networks:
  result-tier:
  poll-tier:
  back-tier: